env: "dev"
db:
  username: "postgres"
  address: "db:5432"
  dbname: "postgres"
  sslmode: "disable"
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s
cache:
  address: "redis:6379"
  db: 0
  state_expiration: 7m
  email_confirmed_code_expiration: 3m
smtp:
  host: "smtp.yandex.ru"
  port: 465
  username: "OfflinerMen@yandex.by"
jwt:
  signing_method: "HS256"
  access_expire: 7m
  refresh_expire: 360h