services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CONFIG_PATH: ${CONFIG_PATH}
      GOOGLE_KEY: ${GOOGLE_KEY}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      YANDEX_EMAIL_PASSWORD: ${YANDEX_EMAIL_PASSWORD}
      YANDEX_KEY: ${YANDEX_KEY}
      YANDEX_SECRET: ${YANDEX_SECRET}
    volumes:
      - avatars:/app/avatars
      - ./config:/config
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
  avatars:
